// Mock content ported from the original single-app frontend/src/types.ts and server.ts.
// Every record keeps its original string id (oldId) plus old-id cross-references so
// seed.ts can remap them to real MongoDB ObjectIds via an idMap as it inserts.

export const USERS = [
  {
    oldId: 'u-1',
    name: 'Karim Bensalah',
    email: 'karim@atlas-trans.ma',
    role: 'transporter' as const,
    status: 'verified' as const,
    companyName: 'Atlas Trans Marrakech',
    phone: '+212 6 61 23 45 67',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    kycDocUrl: 'Licence_Atlas_2026.pdf',
    kycUploadedAt: '2026-01-15',
    ice: '001548796000085',
    patente: '45879621',
    rc: '98455-Marrakech',
    ifFiscal: '12457896',
    cnss: '8547963',
    kycLicenceUrl: 'Licence_Atlas_2026.pdf',
    kycLicenceStatus: 'verified' as const,
    kycRcUrl: 'RC_Atlas_Trans.pdf',
    kycRcStatus: 'verified' as const,
    kycInsuranceUrl: 'Assurance_Passagers_Atlas.pdf',
    kycInsuranceStatus: 'verified' as const,
    kycPatenteUrl: 'Patente_Atlas_2026.pdf',
    kycPatenteStatus: 'verified' as const,
    errorCount: 1,
    riskErrors: [
      { type: 'Retard', date: '2026-07-04', description: 'Retard de 12 minutes au point de prise en charge (Riad Royal Marrakech)', resolved: false },
    ],
  },
  {
    oldId: 'u-2',
    name: 'Sarah El Fassi',
    email: 'sarah@riad-royal.ma',
    role: 'client' as const,
    status: 'verified' as const,
    companyName: 'Riad Royal Marrakech',
    phone: '+212 5 24 88 99 00',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    ice: '002354897000041',
    patente: '35698412',
    rc: '74125-Marrakech',
    ifFiscal: '58412369',
    cnss: '9658231',
  },
  {
    oldId: 'u-3',
    name: 'Youssef Alami',
    email: 'youssef@mumy.ma',
    role: 'admin' as const,
    status: 'verified' as const,
    companyName: 'Mumy HQ',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    oldId: 'u-4',
    name: 'Chauffeur Ahmed',
    email: 'ahmed@driver.ma',
    role: 'driver' as const,
    status: 'verified' as const,
    companyName: 'Atlas Trans Marrakech',
    phone: '+212 6 77 88 99 00',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
  },
  {
    oldId: 'u-5',
    name: 'Mehdi Sahara',
    email: 'mehdi@sahara-rides.ma',
    role: 'transporter' as const,
    status: 'pending' as const,
    companyName: 'Sahara Rides Agadir',
    phone: '+212 6 50 11 22 33',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    kycDocUrl: 'Patente_Sahara_Rides.pdf',
    kycUploadedAt: '2026-07-01',
    ice: '001958473000012',
    patente: '87541296',
    rc: '45872-Agadir',
    ifFiscal: '32587412',
    cnss: '1245873',
    kycLicenceUrl: 'Licence_Sahara_Rides.pdf',
    kycLicenceStatus: 'pending' as const,
    kycRcUrl: 'RC_Sahara_Rides.pdf',
    kycRcStatus: 'pending' as const,
    kycInsuranceUrl: 'Assurance_Sahara_Rides.pdf',
    kycInsuranceStatus: 'missing' as const,
    kycPatenteUrl: 'Patente_Sahara_Rides.pdf',
    kycPatenteStatus: 'pending' as const,
    errorCount: 0,
    riskErrors: [],
  },
];

// Deterministic per-role demo passwords, printed to console after seeding.
export const DEMO_PASSWORDS: Record<string, string> = {
  admin: 'Mumy2026!Admin',
  transporter: 'Mumy2026!Transp',
  client: 'Mumy2026!Client',
  driver: 'Mumy2026!Driver',
};

export const VEHICLES = [
  {
    oldId: 'v-1',
    transporterOldId: 'u-1',
    brand: 'Mercedes-Benz',
    model: 'Sprinter Tourer',
    plate: '12-A-34567',
    capacity: 17,
    status: 'available' as const,
    year: 2024,
    insuranceExpiry: '2026-12-31',
    technicalControlExpiry: '2026-09-15',
    fuelType: 'Gazole' as const,
    mileage: 42500,
    avgConsumption: 9.2,
    notes: 'Climatisation renforcée arrière, Wi-Fi embarqué, sièges en cuir inclinables.',
    maintenanceLogs: [
      { date: '2026-05-10', type: 'oil_change' as const, cost: 1200, description: 'Vidange complète + changement filtre à huile et gazole', provider: 'Sidi Ghanem Auto-Service' },
      { date: '2026-06-25', type: 'tires' as const, cost: 4800, description: 'Remplacement de 2 pneus avant (Michelin Agilis)', provider: 'Atlas Pneus Marrakech' },
    ],
    fuelLogs: [
      { date: '2026-07-02', liters: 65, cost: 850, mileage: 42100 },
      { date: '2026-07-05', liters: 70, cost: 910, mileage: 42500 },
    ],
  },
  {
    oldId: 'v-2',
    transporterOldId: 'u-1',
    brand: 'Hyundai',
    model: 'H1',
    plate: '44-B-9876',
    capacity: 8,
    status: 'on_duty' as const,
    year: 2023,
    insuranceExpiry: '2026-10-30',
    technicalControlExpiry: '2026-11-20',
    fuelType: 'Gazole' as const,
    mileage: 68100,
    avgConsumption: 8.5,
    notes: 'Idéal pour petits groupes VIP et bagages volumineux.',
    maintenanceLogs: [
      { date: '2026-04-12', type: 'brakes' as const, cost: 1500, description: 'Changement plaquettes et disques de frein avant', provider: 'Garage de la Menara' },
    ],
    fuelLogs: [{ date: '2026-07-01', liters: 50, cost: 650, mileage: 67800 }],
  },
  {
    oldId: 'v-3',
    transporterOldId: 'u-1',
    brand: 'Toyota',
    model: 'Prado TX',
    plate: '26-A-5544',
    capacity: 6,
    status: 'maintenance' as const,
    year: 2022,
    insuranceExpiry: '2026-08-15',
    technicalControlExpiry: '2026-08-25',
    fuelType: 'Gazole' as const,
    mileage: 112000,
    avgConsumption: 10.5,
    notes: '4x4 haut de gamme pour excursions désert / Agafay et Atlas.',
    maintenanceLogs: [
      { date: '2026-06-30', type: 'engine' as const, cost: 1500, description: 'Contrôle injecteurs et nettoyage filtre à particules', provider: 'Toyota Succursale Marrakech' },
    ],
    fuelLogs: [{ date: '2026-06-28', liters: 80, cost: 1040, mileage: 111500 }],
  },
];

export const DRIVERS = [
  {
    oldId: 'd-1',
    transporterOldId: 'u-1',
    linkedUserOldId: 'u-4',
    name: 'Ahmed El Mansouri',
    phone: '+212 6 77 88 99 00',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    rating: 4.8,
    status: 'active' as const,
    email: 'ahmed.mansouri@gmail.com',
    licenseNumber: '12/45789-B/D',
    licenseCategory: 'D (Transport en Commun)',
    licenseExpiry: '2029-05-12',
    cnssNumber: '254879612',
    hireDate: '2022-03-01',
    salary: 6500,
    notes: 'Chauffeur bilingue Français/Anglais, excellente présentation, spécialiste excursions Grand Sud.',
    medicalCheckExpiry: '2027-04-15',
    licenseCategories: ['B', 'D'],
  },
  {
    oldId: 'd-2',
    transporterOldId: 'u-1',
    linkedUserOldId: null,
    name: 'Rachid Bouazza',
    phone: '+212 6 11 22 33 44',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    rating: 4.9,
    status: 'active' as const,
    email: 'rachid.b@yahoo.fr',
    licenseNumber: '99/54127-B/D',
    licenseCategory: 'D (Transport en Commun)',
    licenseExpiry: '2028-11-20',
    cnssNumber: '985472145',
    hireDate: '2023-06-15',
    salary: 6000,
    notes: 'Excellente conduite défensive, très apprécié par les clients des hôtels 5 étoiles.',
    medicalCheckExpiry: '2026-10-30',
    licenseCategories: ['B', 'C', 'D'],
  },
  {
    oldId: 'd-3',
    transporterOldId: 'u-1',
    linkedUserOldId: null,
    name: 'Mustapha Touzani',
    phone: '+212 6 55 66 77 88',
    avatarUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&auto=format&fit=crop&q=80',
    rating: 4.5,
    status: 'inactive' as const,
    email: 'mustapha.touz@hotmail.com',
    licenseNumber: '05/88457-B/D',
    licenseCategory: 'D (Transport en Commun)',
    licenseExpiry: '2027-04-10',
    cnssNumber: '114587932',
    hireDate: '2024-01-10',
    salary: 5800,
    notes: 'Actuellement en congé maladie ou indisponible.',
    medicalCheckExpiry: '2026-12-15',
    licenseCategories: ['D'],
  },
];

export const REQUESTS = [
  {
    oldId: 'req-1',
    clientOldId: 'u-2',
    clientName: 'Riad Royal',
    passengerName: 'M. et Mme Dupont',
    origin: 'Aéroport Marrakech-Menara (RAK)',
    destination: 'Riad Royal (Médina)',
    dateTime: '2026-07-04T14:30',
    paxCount: 2,
    serviceType: 'simple' as const,
    status: 'accepted' as const,
    assignedDriverOldId: 'd-1',
    assignedVehicleOldId: 'v-2',
    transporterOldId: 'u-1',
  },
  {
    oldId: 'req-2',
    clientOldId: 'u-2',
    clientName: 'Riad Royal',
    passengerName: 'Groupe Henderson',
    origin: 'Marrakech',
    destination: "Essaouira (Excursion d'une journée)",
    dateTime: '2026-07-05T08:00',
    paxCount: 6,
    serviceType: 'disposal' as const,
    daysCount: 1,
    status: 'pending' as const,
    assignedDriverOldId: null,
    assignedVehicleOldId: null,
    transporterOldId: null,
  },
];

export const BIDS = [
  {
    oldId: 'bid-1',
    requestOldId: 'req-2',
    transporterOldId: 'u-1',
    transporterName: 'Atlas Trans Marrakech',
    priceDHS: 1800,
    vehicleType: 'Hyundai H1 (8 places)',
    status: 'pending' as const,
  },
];

export const EMPTY_RETURNS = [
  {
    oldId: 'empty-1',
    transporterOldId: 'u-1',
    transporterName: 'Atlas Trans Marrakech',
    origin: 'Essaouira',
    destination: 'Marrakech',
    dateTime: '2026-07-05T18:00',
    basePriceDHS: 1000,
    vehicleType: 'Mercedes Sprinter (17 places)',
    status: 'available' as const,
  },
  {
    oldId: 'empty-2',
    transporterOldId: 'u-5',
    transporterName: 'Sahara Rides Agadir',
    origin: 'Taghazout',
    destination: 'Aéroport Agadir Al-Massira',
    dateTime: '2026-07-06T10:00',
    basePriceDHS: 500,
    vehicleType: 'Minibus Toyota (12 places)',
    status: 'available' as const,
  },
];

export const FINANCES = [
  { transporterOldId: 'u-1', date: '2026-06-27', type: 'revenue' as const, amount: 4500, label: "Excursion d'équipe Riad Royal", category: 'Services' },
  { transporterOldId: 'u-1', date: '2026-06-28', type: 'expense' as const, amount: 850, label: 'Plein Gazole Sprinter v-1', category: 'Carburant' },
  { transporterOldId: 'u-1', date: '2026-06-29', type: 'revenue' as const, amount: 1200, label: 'Retour à vide Essaouira-Kech', category: 'Retour à Vide' },
  { transporterOldId: 'u-1', date: '2026-06-30', type: 'expense' as const, amount: 1500, label: 'Maintenance Toyota Prado v-3', category: 'Entretien' },
  { transporterOldId: 'u-1', date: '2026-07-01', type: 'revenue' as const, amount: 3200, label: 'Mise à disposition 3 jours - Agence Travel', category: 'Services' },
  { transporterOldId: 'u-1', date: '2026-07-02', type: 'expense' as const, amount: 400, label: 'Lavage flotte hebdomadaire', category: 'Entretien' },
];

export const TEAM = [
  { transporterOldId: null, name: 'Youssef Alami', email: 'youssef@mumy.ma', role: 'Super Admin', permissions: ['all'] },
  { transporterOldId: null, name: 'Leila Meziane', email: 'leila@mumy.ma', role: 'Modératrice KYC', permissions: ['validate_users', 'view_chat'] },
  { transporterOldId: null, name: 'Amine Radi', email: 'amine@mumy.ma', role: 'Support Client', permissions: ['view_chat', 'resolve_disputes'] },
];

// COLLABORATIVE_CHATS in the original app — the general "public" transporter-to-transporter feed.
// (INITIAL_CHATS, a second mock array in the original types.ts, was never wired into any UI
// state and is intentionally not ported here — confirmed dead data.)
export const COLLAB_CHATS = [
  { senderOldId: 'u-1', senderName: 'Atlas Trans Marrakech', senderRole: 'transporter' as const, message: "Salut confrères, j'ai un Sprinter vide qui rentre d'Essaouira dimanche vers 18h. Si quelqu'un a des clients, je le fais à -50%, soit 1000 DHS net." },
  { senderOldId: 'u-5', senderName: 'Sahara Rides Agadir', senderRole: 'transporter' as const, message: "Intéressant ! J'ai peut-être un groupe de 12 golfeurs à rapatrier. Je te dis dans 10 minutes." },
];

export const SENTIMENT_ALERTS = [
  {
    chatId: '#304',
    sentiment: 'negative' as const,
    message: '⚠️ Alerte Gemini : Risque de litige détecté dans le Chat #304 suite à un retard de vol - Intervention admin recommandée',
  },
];

export const BANNERS = [
  {
    title: 'Offre Spéciale : Équipez votre flotte avec nos boîtiers GPS',
    description: 'Bénéficiez de -20% sur les traceurs GPS professionnels homologués Mumy pour un suivi en direct parfait.',
    imageUrl: 'https://images.unsplash.com/photo-1524508762098-fd966ffb6ef9?w=400&auto=format&fit=crop&q=80',
    linkUrl: 'https://mumy.ma/gps-promo',
    targetRole: 'transporter' as const,
    optimizationType: 'cpc' as const,
    cpcValue: 2.5,
    cpmValue: 15,
    budget: 500,
    spent: 45.0,
    impressions: 1250,
    clicks: 18,
    isActive: true,
  },
  {
    title: 'Assurance Flotte Premium • AXA Maroc',
    description: 'Tarif préférentiel exclusif pour les transporteurs et chauffeurs agréés Mumy. Couverture totale tout risque.',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&auto=format&fit=crop&q=80',
    linkUrl: 'https://axa.ma/partenaires/mumy',
    targetRole: 'transporter' as const,
    optimizationType: 'cpm' as const,
    cpcValue: 1.8,
    cpmValue: 12,
    budget: 300,
    spent: 24.0,
    impressions: 2000,
    clicks: 15,
    isActive: true,
  },
  {
    title: 'Besoin de transferts supplémentaires ce week-end ?',
    description: 'Réservez en un clic nos vans de luxe de rechange. Service garanti 5 étoiles pour vos clients de Riad.',
    imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&auto=format&fit=crop&q=80',
    linkUrl: 'https://mumy.ma/pro-booking',
    targetRole: 'client' as const,
    optimizationType: 'cpc' as const,
    cpcValue: 3.0,
    cpmValue: 20,
    budget: 600,
    spent: 90.0,
    impressions: 1800,
    clicks: 30,
    isActive: true,
  },
  {
    title: "Restauration Chauffeurs : -15% chez l'Escale Gourmet",
    description: "Présentez votre application de suivi Mumy pour bénéficier d'une réduction sur tous les menus Chauffeurs.",
    imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=400&auto=format&fit=crop&q=80',
    linkUrl: 'https://lescalegourmet.com/chauffeurs-mumy',
    targetRole: 'driver' as const,
    optimizationType: 'cpm' as const,
    cpcValue: 1.0,
    cpmValue: 8,
    budget: 150,
    spent: 8.0,
    impressions: 1000,
    clicks: 22,
    isActive: true,
  },
  {
    title: 'Voyagez sereinement avec Mumy Assistance',
    description: 'Une assistance 24/7 pour tous les clients Pro de nos hôtels partenaires. Suivez votre chauffeur sur notre radar.',
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&auto=format&fit=crop&q=80',
    linkUrl: 'https://mumy.ma/assistance-voyage',
    targetRole: 'public' as const,
    optimizationType: 'cpm' as const,
    cpmValue: 10,
    cpcValue: 1.5,
    budget: 200,
    spent: 5.0,
    impressions: 500,
    clicks: 12,
    isActive: true,
  },
];

// transporterOldId is corrected here to the REAL transporter (u-1 / u-5) rather than the
// original mock's 'u-2'/'u-3' (a client and an admin, respectively) — a data-quality bug
// in the source app, fixed at seed time rather than preserved. transporterName already
// matched the real transporter in the original data, which is how the bug was found.
export const EXCURSIONS = [
  {
    oldId: 'exc-1',
    transporterOldId: 'u-1',
    transporterName: 'Atlas Trans Marrakech',
    title: "Excursion d'une journée aux Cascades d'Ouzoud",
    description: "Échappez à l'agitation de Marrakech pour une journée de randonnée rafraîchissante vers l'une des merveilles naturelles du Maroc : les cascades d'Ouzoud. Admirez des chutes d'eau de 110 mètres de haut, rencontrez des singes macaques en liberté et profitez d'un délicieux tajine au bord de l'eau.",
    duration: '1 jour (08:00 - 18:00)',
    priceDHS: 350,
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&auto=format&fit=crop&q=80',
    location: "Cascades d'Ouzoud",
    maxPax: 15,
    highlights: [
      'Randonnée guidée près des impressionnantes cascades de 110m',
      "Rencontre et photos avec les macaques magots sauvages de l'Atlas",
      'Déjeuner traditionnel berbère dans un restaurant local avec vue panoramique',
      "Option de petite balade en barque artisanale au pied des chutes",
    ],
    includes: [
      'Transport aller-retour en Minivan VIP climatisé',
      'Chauffeur certifié bilingue',
      'Guide de montagne local breveté',
      'Déjeuner complet (Tajine, Couscous, Fruits et Thé)',
    ],
    excludes: ['Boissons supplémentaires', 'Balade en barque (environ 20 DHS/personne)', 'Pourboires et dépenses personnelles'],
    isActive: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=F5gQ0uA7KzQ',
  },
  {
    oldId: 'exc-2',
    transporterOldId: 'u-1',
    transporterName: 'Atlas Trans Marrakech',
    title: "Aventure en Quad & Coucher de Soleil dans le Désert d'Agafay",
    description: "Vivez le frisson d'une escapade dans le désert de pierres d'Agafay, situé aux portes de Marrakech. Traversez les dunes arides en quad, profitez du magnifique coucher de soleil sur les montagnes enneigées de l'Atlas, puis savourez un dîner gastronomique traditionnel sous une tente nomade berbère.",
    duration: '6 heures (16:00 - 22:00)',
    priceDHS: 550,
    imageUrl: 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800&auto=format&fit=crop&q=80',
    location: "Désert d'Agafay",
    maxPax: 20,
    highlights: [
      '2 heures de randonnée guidée en quad double ou individuel',
      "Coucher de soleil spectaculaire sur les canyons d'Agafay",
      'Dîner de prestige sous tente caïdale : soupe, tajine et pâtisseries marocaines',
      'Spectacle de feu marocain envoûtant et animation musicale folklorique Gnaoua',
    ],
    includes: [
      'Prise en charge et retour à votre riad/hôtel à Marrakech',
      'Location du quad de 450cc avec équipement de sécurité (casque, lunettes)',
      'Guide professionnel de quad',
      'Dîner marocain gastronomique traditionnel complet et eau',
    ],
    excludes: ['Boissons gazeuses et alcoolisées', 'Pourboires pour le personnel'],
    isActive: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=z8XvXk5qOTo',
  },
  {
    oldId: 'exc-3',
    transporterOldId: 'u-5',
    transporterName: 'Sahara Rides Agadir',
    title: "Journée d'Évasion à Essaouira - Mogador la Poétique",
    description: "Explorez l'ancienne cité fortifiée d'Essaouira, anciennement connue sous le nom de Mogador. Flânez dans sa médina blanche et bleue classée à l'UNESCO, visitez les remparts fortifiés de la Sqala, dégustez du poisson fraîchement pêché sur le port et laissez-vous bercer par l'ambiance bohème et artistique de la côte atlantique.",
    duration: '1 jour (07:30 - 19:00)',
    priceDHS: 400,
    imageUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&auto=format&fit=crop&q=80',
    location: 'Essaouira',
    maxPax: 12,
    highlights: [
      "Visite libre de la médina magique d'Essaouira classée au patrimoine de l'UNESCO",
      'Exploration de la Sqala de la Kasbah et ses canons portugais en bronze',
      'Déjeuner de poissons et fruits de mer fraîchement pêchés sur le port de pêche',
      'Arrêt panoramique en chemin avec possibilité d\'observer les célèbres chèvres sur les arganiers',
    ],
    includes: [
      'Transport aller-retour en Mercedes Sprinter VIP avec Wi-Fi à bord',
      'Chauffeur de tourisme certifié bilingue',
      "Arrêt visite d'une coopérative féminine d'huile d'argan bio",
      "Bouteilles d'eau minérale pour le trajet",
    ],
    excludes: ['Déjeuner de poisson (libre sur le port ou dans la médina)', 'Guide local facultatif (environ 150 DHS pour le groupe)'],
    isActive: true,
  },
];

export const WEBSITES = [
  {
    transporterOldId: 'u-1',
    transporterName: 'Atlas Trans Marrakech',
    customDomain: 'www.atlas-trans.ma',
    dnsStatus: 'active' as const,
    aRecord: '151.101.1.5',
    cnameRecord: 'dns.mumy.ma',
    siteTitle: 'Atlas Prestige Transports',
    siteSubtitle: 'Chauffeurs Privés & Excursions de Rêve à Marrakech',
    aboutText:
      "Depuis plus de 10 ans, Atlas Prestige Transports est le partenaire privilégié de vos déplacements et aventures au Maroc. Basés à Marrakech, nous exploitons une flotte de véhicules haut de gamme (Mercedes Vito, Sprinter VIP, Range Rover) avec des chauffeurs professionnels bilingues, passionnés par la richesse culturelle de notre pays.",
    primaryColor: '#008060',
    contactEmail: 'contact@atlas-trans.ma',
    contactPhone: '+212 6 61 23 45 67',
    headerImageUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1600&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1549417229-aa67d3263c09?w=200&auto=format&fit=crop&q=80',
    tripadvisorUrl: 'https://www.tripadvisor.com/Attraction_Review-g293734-d12345678-Reviews-Atlas_Prestige_Transports-Marrakech.html',
  },
  {
    transporterOldId: 'u-5',
    transporterName: 'Sahara Rides Agadir',
    customDomain: 'www.sahara-rides.com',
    dnsStatus: 'pending' as const,
    aRecord: '151.101.1.5',
    cnameRecord: 'dns.mumy.ma',
    siteTitle: 'Sahara Rides & Coastal Tours',
    siteSubtitle: 'Découvrez le Sud du Maroc en Sécurité et Grand Confort',
    aboutText:
      "Sahara Rides Agadir est spécialisé dans les circuits côtiers et excursions dans le grand Sud marocain. Notre expertise s'étend d'Agadir à Essaouira, Taghazout, Tafraout et jusqu'aux portes du Sahara à Merzouga. Voyager avec nous, c'est l'assurance d'un service professionnel certifié et d'expériences mémorables.",
    primaryColor: '#eab308',
    contactEmail: 'booking@sahara-rides.com',
    contactPhone: '+212 6 50 11 22 33',
    headerImageUrl: 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=1600&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1603349204300-fe2f54c2a16d?w=200&auto=format&fit=crop&q=80',
    tripadvisorUrl: 'https://www.tripadvisor.com/Attraction_Review-g293731-d87654321-Reviews-Sahara_Rides_Coastal_Tours-Agadir.html',
  },
];

export const SUPPORT_SESSIONS = [
  {
    userOldId: 'u-1',
    userName: 'Karim Bensalah (Atlas Transport)',
    userRole: 'transporter' as const,
    needsHuman: true,
    status: 'pending_human' as const,
    messages: [
      { senderOldId: 'u-1', senderName: 'Karim Bensalah', senderRole: 'transporter' as const, message: "Bonjour, j'aimerais contester l'incident de retard de service enregistré le 4 juillet. Le client est arrivé en retard de son vol." },
      { senderOldId: null, senderName: 'Assistant IA', senderRole: 'agent' as const, message: "Bonjour Karim. J'ai bien noté votre demande. Notre politique permet de réévaluer un incident si vous disposez d'un justificatif (ex: capture d'écran du panneau des vols ou message de l'hôtel). Souhaitez-vous que je transmette votre dossier à un conseiller humain pour validation ?" },
      { senderOldId: 'u-1', senderName: 'Karim Bensalah', senderRole: 'transporter' as const, message: 'Oui, s\'il vous plaît. Transmettez à un agent de support.' },
    ],
  },
  {
    userOldId: 'u-2',
    userName: 'Yasmine Alami (Riad Royal)',
    userRole: 'client' as const,
    needsHuman: false,
    status: 'ai' as const,
    messages: [
      { senderOldId: 'u-2', senderName: 'Yasmine Alami', senderRole: 'client' as const, message: 'Bonjour, j\'essaie de réserver un retour à vide pour Essaouira mais le système m\'affiche complet. Est-ce normal ?' },
      { senderOldId: null, senderName: 'Assistant IA', senderRole: 'agent' as const, message: 'Bonjour Yasmine. Les retours à vide sont extrêmement prisés. Si un trajet n\'est plus visible, c\'est qu\'il a probablement été réservé par un autre établissement. Je vous conseille d\'activer les alertes flash pour recevoir une notification dès qu\'un nouvel itinéraire Essaouira - Marrakech est disponible !' },
    ],
  },
];
